[Icon Theme]
Name=Crux
Name[ar]=كرُكس
Name[as]=ক্ৰুক্স
Name[ast]=Crux
Name[az]=Crux
Name[be]=Сутнасьць
Name[be@latin]=Crux
Name[bg]=Крукс
Name[bn]=জটিল
Name[bn_IN]=ক্রুক্স
Name[br]=Crux
Name[bs]=Crux
Name[ca]=Crux
Name[ca@valencia]=Crux
Name[crh]=Haç Burcu
Name[cs]=Crux
Name[cy]=Crux
Name[da]=Crux
Name[de]=Crux
Name[dz]=གནད་དགག།
Name[el]=Crux
Name[en@shaw]=·𐑒𐑮𐑩𐑒𐑕
Name[en_CA]=Crux
Name[en_GB]=Crux
Name[es]=Crux
Name[et]=Crux
Name[eu]=Gurutzea
Name[fa]=کراکس
Name[fi]=Pulma
Name[fr]=Crux
Name[fur]=Crux
Name[ga]=Crux
Name[gl]=Crux
Name[gu]=ક્રક્ક્ષ
Name[he]=העיקר
Name[hi]=क्रक्स्
Name[hr]=Crux
Name[hu]=Crux
Name[id]=Crux
Name[is]=Crux
Name[it]=Crux
Name[ja]=南十字座
Name[ka]=ჯვარი
Name[kn]=ಕ್ರಕ್ಸ್‌
Name[ko]=남십자성
Name[ku]=Crux
Name[ky]=Түштүк крест
Name[li]=Crux
Name[lt]=Crux
Name[lv]=Crux
Name[mai]=क्रक्स्
Name[mg]=Crux
Name[mk]=Crux
Name[ml]=സങ്കീര്‍ണ്ണമായ പ്രശ്നത്തിന്റെ ഭാഗം
Name[mn]=Хүндрэл
Name[mr]=क्रक्स
Name[ms]=Crux
Name[nb]=Crux
Name[nds]=Crux
Name[ne]=क्रक्स
Name[nl]=Crux
Name[nn]=Crux
Name[oc]=Crux
Name[or]=କ୍ରକ୍ସ
Name[pa]=ਕਰਕਸ਼
Name[pl]=Crux
Name[pt]=Crux
Name[pt_BR]=Crux
Name[ro]=Crux
Name[ru]=Южный крест
Name[si]=ප්‍රහේලිකාව
Name[sk]=Rébus
Name[sl]=Crux
Name[sq]=Crux
Name[sr]=Крукс
Name[sr@latin]=Kruks
Name[sv]=Crux
Name[ta]=கிரஸ்
Name[te]=క్రక్స్
Name[th]=ถึงแก่น
Name[tr]=Crux
Name[ug]=كىرىست بەلگۈسى
Name[uk]=Кракс
Name[vi]=Điểm chính
Name[wa]=Tinme «Crux»
Name[xh]=i-Crux
Name[zh_CN]=十字架
Name[zh_HK]=南十字
Name[zh_TW]=南十字
Comment=Crux
Comment[ar]=كرُكس
Comment[as]=ক্ৰুক্স
Comment[ast]=Crux
Comment[az]=Crux
Comment[be]=Сутнасьць
Comment[be@latin]=Crux
Comment[bg]=Крукс
Comment[bn]=জটিল
Comment[bn_IN]=ক্রুক্স
Comment[br]=Crux
Comment[bs]=Crux
Comment[ca]=Crux
Comment[ca@valencia]=Crux
Comment[crh]=Haç Burcu
Comment[cs]=Crux
Comment[cy]=Crux
Comment[da]=Crux
Comment[de]=Crux
Comment[dz]=གནད་དགག།
Comment[el]=Crux
Comment[en@shaw]=·𐑒𐑮𐑩𐑒𐑕
Comment[en_CA]=Crux
Comment[en_GB]=Crux
Comment[es]=Crux
Comment[et]=Crux
Comment[eu]=Gurutzea
Comment[fa]=کراکس
Comment[fi]=Pulma
Comment[fr]=Crux
Comment[fur]=Crux
Comment[ga]=Crux
Comment[gl]=Crux
Comment[gu]=ક્રક્ક્ષ
Comment[he]=העיקר
Comment[hi]=क्रक्स्
Comment[hr]=Crux
Comment[hu]=Crux
Comment[id]=Crux
Comment[is]=Crux
Comment[it]=Crux
Comment[ja]=南十字座
Comment[ka]=ჯვარი
Comment[kn]=ಕ್ರಕ್ಸ್‌
Comment[ko]=남십자성
Comment[ku]=Crux
Comment[ky]=Түштүк крест
Comment[li]=Crux
Comment[lt]=Crux
Comment[lv]=Crux
Comment[mai]=क्रक्स्
Comment[mg]=Crux
Comment[mk]=Crux
Comment[ml]=സങ്കീര്‍ണ്ണമായ പ്രശ്നത്തിന്റെ ഭാഗം
Comment[mn]=Хүндрэл
Comment[mr]=क्रक्स
Comment[ms]=Crux
Comment[nb]=Crux
Comment[nds]=Crux
Comment[ne]=क्रक्स
Comment[nl]=Crux
Comment[nn]=Crux
Comment[oc]=Crux
Comment[or]=କ୍ରକ୍ସ
Comment[pa]=ਕਰਕਸ਼
Comment[pl]=Crux
Comment[pt]=Crux
Comment[pt_BR]=Crux
Comment[ro]=Crux
Comment[ru]=Южный крест
Comment[si]=ප්‍රහේලිකාව
Comment[sk]=Rébus
Comment[sl]=Crux
Comment[sq]=Crux
Comment[sr]=Крукс
Comment[sr@latin]=Kruks
Comment[sv]=Crux
Comment[ta]=கிரஸ்
Comment[te]=క్రక్స్
Comment[th]=ถึงแก่น
Comment[tr]=Crux
Comment[ug]=كىرىست بەلگۈسى
Comment[uk]=Кракс
Comment[vi]=Điểm chính
Comment[wa]=Tinme «Crux»
Comment[xh]=i-Crux
Comment[zh_CN]=十字架
Comment[zh_HK]=南十字
Comment[zh_TW]=南十字
Inherits=gnome
Directories=16x16/actions,16x16/places,16x16/status,22x22/actions,22x22/places,22x22/status,24x24/actions,24x24/places,24x24/status,32x32/actions,32x32/places,32x32/status,scalable/places,scalable/actions,scalable/status

[16x16/actions]
Size=16
Context=Actions
Type=Fixed

[16x16/status]
Size=16
Context=Status
Type=Fixed

[16x16/places]
Size=16
Context=Places
Type=Fixed

[22x22/actions]
Size=22
Context=Actions
Type=Fixed

[22x22/status]
Size=22
Context=Status
Type=Fixed

[22x22/places]
Size=22
Context=Places
Type=Fixed

[24x24/actions]
Size=24
Context=Actions
Type=Fixed

[24x24/status]
Size=24
Context=Status
Type=Fixed

[24x24/places]
Size=24
Context=Places
Type=Fixed

[32x32/actions]
Size=32
Context=Actions
Type=Fixed

[32x32/status]
Size=32
Context=Status
Type=Fixed

[32x32/places]
Size=32
Context=Places
Type=Fixed

[scalable/actions]
Size=48
Context=Actions
Type=Scalable
MinSize=48
MaxSize=256

[scalable/status]
Size=48
Context=Status
Type=Scalable
MinSize=48
MaxSize=256

[scalable/places]
Size=48
Context=Places
Type=Scalable
MinSize=48
MaxSize=256
